services:
  shortener:
    build:
      context: .
      dockerfile: Dockerfile
    # platform: linux/arm64
    ports:
      - "8080:8080"
    environment:
      - DATABASE_DSN=postgres://postgres:postgres@db:5432/shortener_db?sslmode=disable
    volumes:
      - data:/data
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:14-alpine
    restart: unless-stopped
    # platform: linux/arm64
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: shortener_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d shortener_db"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  db_data:
  data: